FROM quay.io/debezium/connect:2.0
COPY kafka-schema-registry-package-7.0.1-standalone.jar /kafka/libs/kafka-schema-registry-package-7.0.1-standalone.jar
COPY kafka-serde-tools-package-7.0.1-standalone.jar /kafka/libs/kafka-serde-tools-package-7.0.1-standalone.jar
